list(APPEND Module_SRCS
  vtkAbstractMapper.cxx
  vtkAbstractMapper3D.cxx
  vtkAbstractPicker.cxx
  vtkAbstractPropPicker.cxx
  vtkAbstractVolumeMapper.cxx
  vtkActor.cxx
  vtkActor2D.cxx
  vtkActor2DCollection.cxx
  vtkActorCollection.cxx
  vtkAreaPicker.cxx
  vtkAssembly.cxx
  vtkAssemblyNode.cxx
  vtkAssemblyPath.cxx
  vtkAssemblyPaths.cxx
  vtkCamera.cxx
  vtkCellPicker.cxx
  vtkChooserPainter.cxx
  vtkClipPlanesPainter.cxx
  vtkCoincidentTopologyResolutionPainter.cxx
  vtkColorTransferFunction.cxx
  vtkCompositeDataDisplayAttributes.cxx
  vtkCompositePainter.cxx
  vtkCompositePolyDataMapper2.cxx
  vtkCoordinate.cxx
  vtkCuller.cxx
  vtkCullerCollection.cxx
  vtkDefaultPainter.cxx
  vtkDiscretizableColorTransferFunction.cxx
  vtkDisplayListPainter.cxx
  vtkFollower.cxx
  vtkFrustumCoverageCuller.cxx
  vtkGenericRenderWindowInteractor.cxx
  vtkGenericVertexAttributeMapping.cxx
  vtkGlyph3DMapper.cxx
  vtkGPUInfo.cxx
  vtkGPUInfoList.cxx
  vtkGraphicsFactory.cxx
  vtkHardwareSelectionPolyDataPainter.cxx
  vtkHardwareSelector.cxx
  vtkImageActor.cxx
  vtkImageSlice.cxx
  vtkImageMapper.cxx
  vtkImageMapper3D.cxx
  vtkImageProperty.cxx
  vtkImageSliceMapper.cxx
  vtkInteractorObserver.cxx
  vtkInteractorStyle.cxx
  vtkInteractorStyleSwitchBase.cxx
  vtkLight.cxx
  vtkLightCollection.cxx
  vtkLightingPainter.cxx
  vtkLightKit.cxx
  vtkLinesPainter.cxx
  vtkLODProp3D.cxx
  vtkMapper.cxx
  vtkMapper2D.cxx
  vtkObserverMediator.cxx
  vtkPainter.cxx
  vtkPainterDeviceAdapter.cxx
  vtkPainterPolyDataMapper.cxx
  vtkPicker.cxx
  vtkPickingManager.cxx
  vtkPointsPainter.cxx
  vtkPolyDataMapper.cxx
  vtkPolyDataMapper2D.cxx
  vtkPolyDataPainter.cxx
  vtkPolygonsPainter.cxx
  vtkPrimitivePainter.cxx
  vtkProp.cxx
  vtkProp3D.cxx
  vtkProp3DCollection.cxx
  vtkProp3DFollower.cxx
  vtkProperty.cxx
  vtkProperty2D.cxx
  vtkPropAssembly.cxx
  vtkPropCollection.cxx
  vtkPropPicker.cxx
  vtkRenderer.cxx
  vtkRendererCollection.cxx
  vtkRendererDelegate.cxx
  vtkRenderWindow.cxx
  vtkRenderWindowInteractor.cxx
  vtkRepresentationPainter.cxx
  vtkScalarsToColorsPainter.cxx
  vtkShaderDeviceAdapter2.cxx
  vtkStandardPolyDataPainter.cxx
  vtkStringToImage.cxx
  vtkTDxInteractorStyle.cxx
  vtkTDxInteractorStyleCamera.cxx
  vtkTDxInteractorStyleSettings.cxx
  vtkTextMapper.cxx
  vtkTextProperty.cxx
  vtkTextRenderer.cxx
  vtkTexture.cxx
  vtkTexturedActor2D.cxx
  vtkTStripsPainter.cxx
  vtkViewport.cxx
  vtkVolume.cxx
  vtkVolumeCollection.cxx
  vtkVolumeProperty.cxx
  vtkWindowToImageFilter.cxx
  vtkWorldPointPicker.cxx
  )