list(APPEND Module_SRCS
  vtkAbstractContextBufferId.cxx
  vtkAbstractContextItem.cxx
  vtkBrush.cxx
  vtkContext2D.cxx
  vtkContext3D.cxx
  vtkContextActor.cxx
  vtkContextClip.cxx
  vtkContextDevice2D.cxx
  vtkContextDevice3D.cxx
  vtkContextItem.cxx
  vtkContextKeyEvent.cxx
  vtkContextMapper2D.cxx
  vtkContextMouseEvent.cxx
  vtkContextScene.cxx
  vtkContextTransform.cxx
  vtkPen.cxx
  vtkTooltipItem.cxx
  )