list(APPEND Module_SRCS
  vtk3DWidgetRepresentation.cxx
  vtkCaveSynchronizedRenderers.cxx
  vtkIceTSynchronizedRenderers.cxx
  vtkMPIMoveData.cxx
  vtkCacheSizeKeeper.cxx
  vtkChartRepresentation.cxx
  vtkChartSelectionRepresentation.cxx
  vtkClientServerMoveData.cxx
  vtkCompositeRepresentation.cxx
  vtkCubeAxesRepresentation.cxx
  vtkDataLabelRepresentation.cxx
  vtkGeometryRepresentation.cxx
  vtkGeometryRepresentationWithFaces.cxx
  vtkGlyph3DRepresentation.cxx
  vtkOutlineRepresentation.cxx
  vtkPVCacheKeeper.cxx
  vtkPVCacheKeeperPipeline.cxx
  vtkPVClientServerSynchronizedRenderers.cxx
  vtkPVCompositeRepresentation.cxx
  vtkPVContextView.cxx
  vtkPVDataDeliveryManager.cxx
  vtkPVDataRepresentation.cxx
  vtkPVDataRepresentationPipeline.cxx
  vtkPVDisplayInformation.cxx
  vtkPVHardwareSelector.cxx
  vtkPVImplicitPlaneRepresentation.cxx
  vtkPVLastSelectionInformation.cxx
  vtkPVPlotMatrixView.cxx
  vtkPVProminentValuesInformation.cxx
  vtkPVRenderView.cxx
  vtkPVRenderViewSettings.cxx
  vtkPVRepresentedDataInformation.cxx
  vtkPVSelectionInformation.cxx
  vtkPVStreamingPiecesInformation.cxx
  vtkPVSynchronizedRenderer.cxx
  vtkPVSynchronizedRenderWindows.cxx
  vtkPVView.cxx
  vtkSelectionDeliveryFilter.cxx
  vtkSelectionRepresentation.cxx
  )