list(APPEND Module_SRCS
  vtkCompositeDataReader.cxx
  vtkCompositeDataWriter.cxx
  vtkDataReader.cxx
  vtkDataWriter.cxx
  vtkDataSetReader.cxx
  vtkDataSetWriter.cxx
  vtkGenericDataObjectReader.cxx
  vtkGenericDataObjectWriter.cxx
  vtkGraphReader.cxx
  vtkGraphWriter.cxx
  vtkPolyDataReader.cxx
  vtkPolyDataWriter.cxx
  vtkRectilinearGridReader.cxx
  vtkRectilinearGridWriter.cxx
  vtkStructuredGridReader.cxx
  vtkStructuredGridWriter.cxx
  vtkStructuredPointsReader.cxx
  vtkStructuredPointsWriter.cxx
  vtkTableReader.cxx
  vtkTableWriter.cxx
  vtkTreeReader.cxx
  vtkTreeWriter.cxx
  vtkUnstructuredGridReader.cxx
  vtkUnstructuredGridWriter.cxx
  )