list(APPEND Module_SRCS
  vtkAxis.cxx
  vtkAxisExtended.cxx
  vtkChart.cxx
  vtkChartLegend.cxx
  vtkChartMatrix.cxx
  vtkChartParallelCoordinates.cxx
  vtkChartXY.cxx
  vtkChartXYZ.cxx
  vtkContextPolygon.cxx
  vtkPlot.cxx
  vtkPlot3D.cxx
  vtkPlotBag.cxx
  vtkPlotBar.cxx
  vtkPlotFunctionalBag.cxx
  vtkPlotGrid.cxx
  vtkPlotLine.cxx
  vtkPlotParallelCoordinates.cxx
  vtkPlotPoints.cxx
  vtkPlotPoints3D.cxx
  vtkPlotStacked.cxx
  vtkScatterPlotMatrix.cxx
  )